### PR TITLE
Move configuration setting to correct place

### PR DESCRIPTION
**Pull request by janmarthedal**
From `fos_user.user_manager` to `fos_user.service.user_manager`

### CODE REVIEW

**Comment by XWB** [comment]
Could you fix the tests?

**Comment by stof** [comment]
@XWB broken tests are because the PHP 7 version on Travis now uses PHPUnit 6 and our testsuite is not yet compatible. It is not related to this PR.

**Comment by XWB** [comment]
Ah, I see. Thanks @stof

**Comment by XWB** [comment]
Thanks.

**Pull request merged**
